export const BUILTIN_MODULES = new Set([
  'cube',
  'sphere',
  'cylinder',
  'circle',
  'square',
  'polygon',
  'polyhedron',
  'text',
  'surface',
  'import',
  'translate',
  'rotate',
  'scale',
  'mirror',
  'multmatrix',
  'resize',
  'offset',
  'color',
  'render',
  'projection',
  'group',
  'union',
  'difference',
  'intersection',
  'hull',
  'minkowski',
  'linear_extrude',
  'rotate_extrude',
  'echo',
  'assert',
  'let',
  'children',
  'intersection_for',
  'parent_module',
]);

export const BUILTIN_SIGNATURES: Record<string, string[]> = {
  'cube': ['size', 'center'],
  'cylinder':
      ['h', 'r', 'r1', 'r2', 'd', 'd1', 'd2', 'center', '$fn', '$fa', '$fs'],
  'sphere': ['r', 'd', '$fn', '$fa', '$fs'],
  'square': ['size', 'center'],
  'circle': ['r', 'd', '$fn', '$fa', '$fs'],
  'polygon': ['points', 'paths', 'convexity'],
  'polyhedron': ['points', 'faces', 'convexity'],
  'linear_extrude': [
    'height', 'v', 'scale', 'center', 'twist', 'slices', 'segments',
    'convexity', 'h', '$fn', '$fa', '$fs', '$fe'
  ],
  'rotate_extrude': ['angle', 'convexity', '$fn'],
  'text': [
    'text', 'size', 'font', 'halign', 'valign', 'spacing', 'direction',
    'language', 'script', '$fn'
  ],
  'surface': ['file', 'center', 'invert', 'convexity'],
  'import': ['file', 'convexity', 'layer'],
  'projection': ['cut'],
  'translate': ['v'],
  'rotate': ['a', 'v'],
  'scale': ['v'],
  'resize': ['newsize', 'auto'],
  'mirror': ['v'],
  'multmatrix': ['m'],
  'color': ['c', 'alpha'],
  'offset': ['r', 'delta', 'chamfer'],
};

export const BUILTIN_FUNCTIONS = new Set([
  'is_undef',    'is_bool',     'is_num',        'is_string', 'is_list',
  'is_function', 'sin',         'cos',           'tan',       'asin',
  'acos',        'atan',        'atan2',         'abs',       'sign',
  'floor',       'ceil',        'round',         'sqrt',      'exp',
  'ln',          'log',         'pow',           'min',       'max',
  'norm',        'cross',       'len',           'str',       'chr',
  'ord',         'concat',      'search',        'lookup',    'rands',
  'version',     'version_num', 'parent_module',
]);

// Experimental or Enable only builtins
export const EXPERIMENTAL_BUILTIN_FUNCTIONS = new Set([
  'is_object',
]);

// Builtins that always return a number when called with arity
export const NUMERIC_BUILTINS = new Map<string, number>([
  ['sin', 1],
  ['cos', 1],
  ['tan', 1],
  ['asin', 1],
  ['acos', 1],
  ['atan', 1],
  ['atan2', 2],
  ['abs', 1],
  ['sign', 1],
  ['floor', 1],
  ['ceil', 1],
  ['round', 1],
  ['sqrt', 1],
  ['exp', 1],
  ['ln', 1],
  ['log', 1],
  ['pow', 2],
]);


export const RUNTIME_SYMBOLS: string[] = [
  'Manifold',
  'CrossSection',
  'wasm',
  'cube',
  'square',
  'sphere',
  'cylinder',
  'circle',
  'radius',
  'rotate',
  'polygon',
  'polyhedron',
  'translate',
  'scale',
  'mirror',
  'resize',
  'is_undef',
  'is_bool',
  'is_num',
  'is_string',
  'is_list',
  'is_function',
  'unknown_fn',
  'sin',
  'cos',
  'tan',
  'asin',
  'acos',
  'atan',
  'atan2',
  'abs',
  'sign',
  'floor',
  'ceil',
  'round',
  'sqrt',
  'exp',
  'ln',
  'log',
  'pow',
  'min',
  'max',
  'norm',
  'cross',
  'len',
  'str',
  'chr',
  'ord',
  'concat',
  'search',
  'lookup',
  'rands',
  'assert',
  'truthy',
  'eq',
  'lt',
  'gt',
  'le',
  'ge',
  'add',
  'sub',
  'mul',
  'div',
  'mod',
  'band',
  'bor',
  'shl',
  'shr',
  'bnot',
  'neg',
  'pos',
  'index',
  'version',
  'version_num',
  'ctx',
  'withSpecials',
  'children_stack',
  'with_children',
  'pick_children',
  'parent_module',
  'is_finite_matrix4',
  'to_manifold_mat4',
  'transform',
  'identity4',
  'offset',
  'projection',
  'color',
  'each',
  'flat_map_iter',
  'range',
  'rangeCount',
  'is2D',
  'union',
  'difference',
  'intersection',
  'hull',
  'minkowski',
  'rootMod',
  'applyRoot',
  'linear_extrude',
  'rotate_extrude',
  'text',
  'parse_color_for_scope',
  'surface',
  'echo',
  'oecho',
  'fnlit',
  'font_registry',
  'tc',
  'call',
];

export const RUNTIME_BUILTIN_MODULES = new Set([
  'cube',       'square',       'sphere',         'cylinder',       'circle',
  'polygon',    'polyhedron',   'text',           'surface',        'translate',
  'rotate',     'scale',        'mirror',         'resize',         'offset',
  'projection', 'color',        'linear_extrude', 'rotate_extrude', 'union',
  'difference', 'intersection', 'hull',           'minkowski',      'echo',
]);
export const RUNTIME_BUILTIN_FUNCTIONS =
    new Set<string>([...BUILTIN_FUNCTIONS, 'assert']);

// Constants the runtime pre-declares as ordinary bindings
export const BUILTIN_VAR_CONSTANTS = ['PI', 'INF', 'NAN', 'undef', '_EPSILON'];
