import {createCanvas, Image} from 'canvas';
import path from 'path';

import type {Argument} from './ast.js';
import {compileExpr, findArg} from './expr.js';
import {T} from './naming.js';
import type {SurfaceAsset} from './state.js';
import {encounteredSurfaceData, globalFileResolver, RT} from './state.js';

// Decodes an image to raw pixels at compile time so the runtime never has to
async function decodeImagePixels(filePath: string):
    Promise<{width: number, height: number, rgb: string}|undefined> {
  const img = new Image();
  // A Buffer src decodes in place; the typings only admit a string
  (img as {src: unknown}).src = await globalFileResolver?.readBinary(filePath);
  const {width, height} = img;
  if (!width || !height) return undefined;

  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');
  ctx.drawImage(img, 0, 0);
  const {data} = ctx.getImageData(0, 0, width, height);

  // Drop the alpha channel: surface() only reads luminance
  const rgb = Buffer.allocUnsafe(width * height * 3);
  for (let i = 0, j = 0; j < rgb.length; i += 4, j += 3) {
    rgb[j] = data[i]!;
    rgb[j + 1] = data[i + 1]!;
    rgb[j + 2] = data[i + 2]!;
  }
  return {width, height, rgb: rgb.toString('base64')};
}

// Writes a `surface()` data file and returns its exported symbol, or warns on
// failure
async function emitSurfaceData(
    filenameStr: string, basePath: string): Promise<SurfaceAsset|undefined> {
  const filePath = path.resolve(basePath, filenameStr);
  if (!await globalFileResolver?.exists(filePath)) {
    console.warn(`Warning: surface("${filenameStr}"): can't open file "${
        filePath}", ignoring.`);
    return undefined;
  }

  // OpenSCAD treats only PNG as an image; everything else is a text matrix
  const isImage = path.extname(filePath).toLowerCase() === '.png';
  const stem = path.basename(filenameStr, path.extname(filenameStr))
                   .replace(/[^a-zA-Z0-9_]/g, '_');

  const currentFileDir = typeof __dirname !== 'undefined' ?
      __dirname :
      path.dirname(
          new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/i, '$1'));
  const surfaceDataDir =
      path.join(path.resolve(currentFileDir, '..'), 'runtime', 'surface_data');
  await globalFileResolver?.makeDir(surfaceDataDir);

  const write = async (body: string) => await globalFileResolver?.writeText(
      path.join(surfaceDataDir, `${stem}_data.ts`),
      `// Auto-generated by OpenSCAD compiler — do not edit\n` +
          `// Source: ${filePath}\n` + body);

  if (isImage) {
    const pixels = await decodeImagePixels(filePath);
    if (!pixels) {
      console.warn(`Warning: surface("${filenameStr}"): can't decode image "${
          filePath}", ignoring.`);
      return undefined;
    }
    const exportName = T(`img_${stem}`);
    await write(
        `// ${pixels.width}x${pixels.height}, base64 of 3 bytes (RGB) per ` +
        `pixel, row-major from the top-left\n` +
        `export const ${exportName} = { width: ${pixels.width}, height: ${
            pixels.height}, rgb: "${pixels.rgb}" };\n`);
    return {stem, exportName, kind: 'image'};
  }

  // Text matrix (.dat / .txt): embed the raw content as a string literal
  const exportName = T(`surfacedata_${stem}`);
  await write(`export const ${exportName} = ${
      JSON.stringify(await globalFileResolver?.readText(filePath))};\n`);
  return {stem, exportName, kind: 'text'};
}

// compile surface
export async function compileSurface(
    args: Argument[], sourceFile: string): Promise<string> {
  const file = findArg(args, 'file', 0);
  const center = findArg(args, 'center', 1);
  const invert = findArg(args, 'invert', 2);

  if (!file?.value || file.value.kind !== 'string') {
    console.warn(`Warning: surface(): no file argument given, ignoring.`);
    return 'Manifold.union([])';
  }
  const filenameStr = file.value.value;

  // `surface()` resolves files relative to the calling `.scad` file
  const basePath =
      sourceFile ? path.dirname(path.resolve(sourceFile)) : process.cwd();

  // `emitSurfaceData` warns and returns `undefined` if the file is missing or
  // invalid
  const asset = await emitSurfaceData(filenameStr, basePath);
  if (!asset) return 'Manifold.union([])';
  encounteredSurfaceData.set(filenameStr, asset);

  const centerStr = center ? compileExpr(center.value) : 'false';
  // invert only reaches the image path; a text matrix has no pixels to flip
  const opts = asset.kind === 'image' ?
      `center: ${centerStr}, invert: ${
          invert ? compileExpr(invert.value) : 'false'}, kind: "image"` :
      `center: ${centerStr}, kind: "text"`;

  return `${RT.surface}(${asset.exportName}, { ${opts}, fn: ${
      RT.ctx}.$fn, fa: ${RT.ctx}.$fa, fs: ${RT.ctx}.$fs })`;
}
