name: publish_npm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    steps:
    - uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 25
        registry-url: 'https://registry.npmjs.org/'

    - name: Update npm # Ensure npm 11.5.1 or later for trusted publishing
      run: npm install -g npm@latest

    - name: Download built examples
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: manifold.yml
        workflow_conclusion: completed
        branch: master
        check_artifacts: true
        name: wasm
        path: ./bindings/wasm/

    - name: Publish to npm
      run: |
        cd ./bindings/wasm/
        npm ci
        npm publish
